Docker java debug
ONSdigital/rm-docker-dev pull request #6
Opened 2017-11-22 13:41 UTC by madeye-matt

- Added JAVA_OPTS definitions for all the containers running Java services
- Converted all environment variables from part1.part to PART1_PART2

2017-11-22 14:13 UTC, jwgwalton commented
need to turn off travis on this repo

2017-11-22 14:56 UTC, benjefferies requested changes

2017-11-22 14:56 UTC, benjefferies commented on .env
> +CASE_DEBUG_PORT=5171
I wonder if we need any of these in the .env file or would it be easier to keep in the compose file?

2017-11-22 16:00 UTC, benjefferies approved these changes

2017-11-22 16:04 UTC, benjefferies commented on .env
> +CASE_DEBUG_PORT=5171
We discussed this and we should look at it again when refactoring the compose file

2017-11-22 16:04 UTC, benjefferies commented on .env
> +CASE_DEBUG_PORT=5171
We discussed this and we should look at it again when refactoring the compose file

2017-11-23 08:46 UTC, jwgwalton approved these changes

2017-11-23 08:46 UTC, merged